# Nom de l'application
spring.application.name=quizify

# Connexion MySQL
# On ajoute serverTimezone et useSSL=false pour éviter les warnings courants
spring.datasource.url=jdbc:mysql://localhost:3306/quizify_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- FIX POUR L'ERREUR "RESERVED" ---
# On force Hibernate à utiliser le dialecte MySQL sans poser de questions à la base de données
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# --- DÉSACTIVER LA SÉCURITÉ ---
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# --- CONFIGURATION EMAIL ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moxekeep@gmail.com
spring.mail.password=dxhh lywz uuez xosr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true